.ORIG x5000           
TRAP41_HANDLER
    JSR DISPLAY     ; Call the existing print routine
    RTI             ; Return from TRAP


DISPLAY
ST R7, SAVE_R7_DISPLAY
ST R0, NUM_TO_DISPLAY
ST R0, ORIGINAL_NUM

LD R0, NUM_TO_DISPLAY
BRzp SKIP_NEGATIVE_PRINT
LD R0, HYPHEN_ASCII
OUT
LD R0, NUM_TO_DISPLAY
NOT R0, R0
ADD R0, R0, #1
ST R0, NUM_TO_DISPLAY

SKIP_NEGATIVE_PRINT
LD R0, FALSE
ST R0, SHOULD_PRINT

; --- Thousands ---
LD R0, NUM_TO_DISPLAY
LD R1, THOUSAND
JSR DIVIDE
ST R0, DIGIT_TO_PRINT
ST R1, NUM_TO_DISPLAY

ADD R0, R0, #0
BRz SKIP_SET_PRINT_FLAG_THOUSAND
LD R0, TRUE
ST R0, SHOULD_PRINT
SKIP_SET_PRINT_FLAG_THOUSAND

LD R0, SHOULD_PRINT
BRz SKIP_PRINT_THOUSAND
LD R0, DIGIT_TO_PRINT
LD R1, ASCII_OFFSET
ADD R0, R0, R1
OUT
SKIP_PRINT_THOUSAND

; --- Hundreds ---
LD R0, NUM_TO_DISPLAY
LD R1, HUNDRED
JSR DIVIDE
ST R0, DIGIT_TO_PRINT
ST R1, NUM_TO_DISPLAY

ADD R0, R0, #0
BRz SKIP_SET_PRINT_FLAG_HUNDRED
LD R0, TRUE
ST R0, SHOULD_PRINT
SKIP_SET_PRINT_FLAG_HUNDRED

LD R0, SHOULD_PRINT
BRz SKIP_PRINT_HUNDREDS
LD R0, DIGIT_TO_PRINT
LD R1, ASCII_OFFSET
ADD R0, R0, R1
OUT
SKIP_PRINT_HUNDREDS

; --- Tens ---
LD R0, NUM_TO_DISPLAY
LD R1, TEN
JSR DIVIDE
ST R0, DIGIT_TO_PRINT
ST R1, NUM_TO_DISPLAY

ADD R0, R0, #0
BRz SKIP_SET_PRINT_FLAG_TENS
LD R0, TRUE
ST R0, SHOULD_PRINT
SKIP_SET_PRINT_FLAG_TENS

LD R0, SHOULD_PRINT
BRz SKIP_PRINT_TENS
LD R0, DIGIT_TO_PRINT
LD R1, ASCII_OFFSET
ADD R0, R0, R1
OUT
SKIP_PRINT_TENS

; --- Ones ---
LD R0, NUM_TO_DISPLAY
LD R1, ASCII_OFFSET
ADD R0, R0, R1
OUT

LD R0, ORIGINAL_NUM
LD R7, SAVE_R7_DISPLAY
RET

; ===== Divide Subroutine =====


DIVIDE
ST R7, SAVE_R7_DIVIDE
ST R0, DIVIDEND
ST R1, DIVISOR

AND R0, R0, #0
ST R0, QUOTIENT

DIVISION_LOOP
LD R0, DIVIDEND
LD R1, DIVISOR
NOT R1, R1
ADD R1, R1, #1
ADD R0, R0, R1
BRn END_DIVISION_LOOP

ST R0, DIVIDEND
LD R0, QUOTIENT
ADD R0, R0, #1
ST R0, QUOTIENT
BRnzp DIVISION_LOOP

END_DIVISION_LOOP
LD R0, DIVIDEND
ST R0, REMAINDER

LD R0, QUOTIENT
LD R1, REMAINDER
LD R7, SAVE_R7_DIVIDE
RET

; =;=;=;=;= vars =;=;=;==
SAVE_R7_DISPLAY .FILL #0
ORIGINAL_NUM    .FILL #0
NUM_TO_DISPLAY  .FILL #0
DIGIT_TO_PRINT  .FILL #0

SAVE_R7_DIVIDE  .FILL #0
DIVIDEND        .FILL #0
DIVISOR         .FILL #0
QUOTIENT        .FILL #0
REMAINDER       .FILL #0

THOUSAND        .FILL #1000
HUNDRED         .FILL #100
TEN             .FILL #10
ASCII_OFFSET    .FILL #48
HYPHEN_ASCII    .FILL #45
TRUE            .FILL #1
FALSE           .FILL #0
SHOULD_PRINT    .FILL #0

.END
